### ISSUE TITLE
Compiled release

### ISSUE THREAD

**Issue by Keith94** [emileber/CrosshairOverlay#3]
Can you release a compiled build for this application?

**Comment by emileber** [comment]
Yes I could, I'll check that in the next few days

**Comment by Keith94** [comment]
Any news on releasing a build?

**Comment by emileber** [comment]
I do not use my windows computer anymore, so until I get to it, it'd be faster for you to just open the project in visual studio and compile it.

**Comment by Keith94** [comment]
OK, thanks. I will give it a try.
